.plzconfig, build_defs/go.build_defs
cc @Garbett1
I think optional_outs is a lightweight way of starting here. Might want to change later.
=> Add basic split debug info support

build_defs/go.build_defs
The `looks_like_build_label` builtin function was added to Please in https://github.com/thought-machine/please/pull/2380 (v16.20.0-beta.14), so there's no need for a Please version bump in `.plzconfig`.
=> Use `looks_like_build_label` builtin to identify build labels

build_defs/go.build_defs
Can't remember why this was only being applied to the server mode (i.e. IDE) but I guess it makes sense it is applied for the CLI as well. This will reduce some friction between different versions of delve and the go binary.
=> Apply check-go-version=false delve flag to either mode of debugging 

build_defs/go.build_defs
This is a way of getting a Go toolchain off the local machine, compiling the stdlib for us.
This is necessary for Go 1.20+ on Alpine where we need to compile the stdlib, but we also can't download a musl-compatible build from `golang.org` (it bombs out moaning about `libresolv.so`).
=> Add go_system_toolchain

build_defs/go.build_defs, tools/please_go/test/write_test_main.go
All the redirection and tee stuff is a bit ugly. It's nicer for the test to just handle this itself.
This is really awkward to do with Go because `testing` doesn't let you configure what it writes to, and `os.Stdout` is a `File` not an `io.Writer`. I think it's worth it though.
=> Remove tee from test command line

.plzconfig, build_defs/go.build_defs
Leverages #93 to add support for it (which is pretty easy now we have the stdlib to hand). It's very similar to build modes overall.
=> Support the race detector

build_defs/go.build_defs, tools/driver/BUILD, tools/driver/main.go, tools/driver/packages/packages.go, tools/please_go/packageinfo/packageinfo.go, tools/please_go/please_go.go
This seems to do what `golangci-lint` wants. It's just pointing to the full compiled `.a` file - I have another branch that was trying to build its own minimal export data file but it seems to more or less end up that you need to basically compile the whole thing.  That may deserve some separate thought - I've heard mentions of being able to use those for more efficient caching (although that might be tricky, but maybe it is conceptually similar to the C++ rules and how the headers work there, which is sort of cooler in terms of incrementality, albeit more complex).
=> Support for ExportFile in Go packages driver

build_defs/go.build_defs, test/buildinfo/BUILD, test/buildinfo/buildinfo_test.go, tools/please_go/modinfo/modinfo.go, tools/please_go/please_go.go
Before: 
```
$ go version -m plz-out/bin/tools/please_go/please_go
plz-out/bin/tools/please_go/please_go: go1.20.3
```
Now:
```
$ go version -m plz-out/bin/tools/please_go/please_go
plz-out/bin/tools/please_go/please_go: go1.20.3
path	github.com/please-build/go-rules/tools/please_go
mod	github.com/please-build/go-rules		
dep	github.com/dustin/go-humanize	v1.0.0	
dep	github.com/peterebden/buildtools	ce40803f44fb09c5cf60b5554fe5819d02df23fc	
dep	github.com/peterebden/go-cli-init/v5	v5.1.0	
dep	github.com/thought-machine/go-flags	v1.6.0	
dep	golang.org/x/crypto	v0.0.0-20210920023735-84f357641f63	
dep	golang.org/x/mod	v0.5.0	
dep	golang.org/x/sys	039c03cc5b867cd7b06a19ff375be5c945c80b10	
dep	golang.org/x/term	v0.0.0-20210615171337-6886f2dfbf5b	
dep	golang.org/x/tools	v0.4.0	
dep …
```
=> Fix buildinfo for go version

build_defs/go.build_defs
=> Add resources argument to go_benchmark

tools/BUILD
The architecture-specific subrepo references in `//tools:download_test` aren't meaningful outside the go-rules repo, causing `plz query graph` to fail with the following error in any parent repo that includes go-rules:
```
CRITICAL: Target ///darwin_amd64//tools:please_go not found in build graph
```
Refactor the downloading of `please_go` and the download test to avoid making subrepo references that might not exist in other contexts.
Fixes #135.
=> Refactor `please_go` download test to avoid subrepo references

build_defs/cgo.build_defs, build_defs/go.build_defs
gcov is part of the GCC toolchain - rather than explicitly linking to libgcov in the coverage profile, pass the `--coverage` flag to the compiler toolchain (which is recognised by both GCC and LLVM).
=> Remove implicit dependency on GCC toolchain

.plzconfig, plugins/BUILD, test/goget/BUILD
This fixes the build in `//test/goget:go_get_test` on recent plz versions.
I'm not sure precisely what's happening but it seems wrong; it works in 17.0.0 but in 17.2.0 that package becomes unbuildable without an extra subinclude. This seems like an inadvertent breaking change.
I'm not particularly interested in trying to debug it right now though, I just want to figure out why my build is broken for #157
=> Update plz version & add subinclude

build_defs/go.build_defs, tools/please_go/generate/generate.go, tools/please_go/generate/rules.go, tools/please_go/modinfo/modinfo.go, tools/please_go/please_go.go
These are a bit trickier because they generate `go_library`s which don't directly depend on anything central to attach this to, so we generate one for each of them.
=> Add modinfo to go_repo actions

build_defs/go.build_defs
When an `url` is provided, we cannot set a version. But `semver_check()` fail if the version is empty.
Just skip the version check and let the user set `install_std` if needed for it go toolchain version.
=> fix: dont check toolchain version when version is not provided

README.md
This change fixes missing documentation about the Golang's new change to the standard library.
=> FIX: Update the README

build_defs/go.build_defs
It's pulling down a whole transitive dependency tree but only needs the `.modinfo` files. This makes it significantly more efficient by matching up require/provide so it only fetches the files it needs.
=> Make modinfo generation more efficient

build_defs/go.build_defs
This allows us to get the .h files of go_libraries we depend on. This is useful for cases such as this:
https://github.com/cloudflare/circl/blob/main/dh/x448/curve_amd64.s
Where we want to include a header from a dep using `../../math/fp448/fp_amd64.h`
We should do this through the normal require/provide setup once we figure out https://github.com/thought-machine/please/pull/2931#pullrequestreview-1694684974
=> Abi hdrs from deps

.plzconfig, build_defs/go.build_defs, tools/please_go/modinfo/BUILD, tools/please_go/modinfo/modinfo.go, tools/please_go/modinfo/modinfo_test.go, tools/please_go/please_go.go
This introduces a new plugin option, `validate_module_version`, that performs sanity checks on the module name and version strings for third-party Go modules downloaded with `go_mod_download`. When enabled, only version strings that conform to Go's module version numbering policy are permitted.
So, with `validate_module_version = true` in `.plzconfig`:
```
$ cat t/BUILD
subinclude("//build_defs:go")
go_module(
name = "go-pluralize",
install = ["..."],
licences = ["MIT"],
module = "github.com/gertd/go-pluralize",
version = "v0.2.0",
)
$ plz build //t:go-pluralize
Build finished; total time 4.11s, incrementality 95.8%. Outputs:
//t:go-pluralize:
plz-out/gen/t/pkg/linux_amd64/github.com/gertd/go-pluralize
```
but:
```
$ cat t/BUILD
subinclude("//build_defs:go")
go_module(
name = …
```
=> Optionally validate `version` parameter in `go_mod_download`

build_defs/go.build_defs
Before we would resolve `-I.` to the directory where we generated the subrepo which would be different to the location when actually compiling the go_library because the subrepo has a package root set. This makes sure that the paths are the same at generate and build time.
=> go_repo: Generate subrepo with the same package root as when building a target in the subrepo

tools/driver/packages/packages.go
Currently we just bomb out because that isn't literally a file; the first thing I tested this with was `gosec` which seemingly handles the `...` itself but `golangci-lint` seems to pass it through literally to us.
Really also wants an extension to plz to allow `whatinputs` to ignore unknown files or it tends to blow up pretty quickly.
=> Support /... paths in package driver

build_defs/go.build_defs
This brings `go_binary` in line with `go_test` and similar rules in other languages.
=> `go_binary`: accept list or dict for `data` parameter

tools/please_go/goget/go_get.go
Now outputs 
```
2024/03/04 16:35:25 Module spec github.com/redis/go-redis/v9 is missing a version; must be in the format golang.org/x/sys@v1.0.0
```
Fixes #238
=> Don't panic if not given a module version

go.mod, tools/please_go/go.mod, tools/please_go/packageinfo/packageinfo.go
This just cuts a bunch of noise out of the package driver output; we don't need to output all the `cmd/` packages (these can't actually be imported anyway because they're not in the importconfig file)
=> Filter stdlib from package_info.json

build_defs/go.build_defs, test/testing_definition/BUILD, test/testing_definition/testing_definition_test.go
Turns out we are meant to set this within tests; since go1.21 `testing.Testing()` is a thing but it's always returning false for us.
Testing strategy for this PR:
Have used the word "test" and "testing" about a hundred thousand times so it must indeed work.
=> testing.Testing() returns true during tests.

.plzconfig, build_defs/go.build_defs
`cgo_enabled` has slightly awkward semantics. The help text and the name imply it's a boolean, but it's actually a string that requires an integer-looking value. In some parts of the Go build defs, the value is expected to be `1`, otherwise cgo won't be enabled; in others, any true value is sufficient to enable cgo (although the value of `CGO_ENABLED` that is passed through to the underlying tool isn't always guaranteed to be `1` - it could even be whatever value is set in the plugin configuration).
Explicitly define `cgo_enabled` as a boolean whose default value is false, matching the current semantics, and ensure that the `CGO_ENABLED` environment variable is set to `1` whenever `cgo_enabled` is true.
=> Convert `cgo_enabled` plugin config field into a boolean

.plzconfig, build_defs/go.build_defs
Whether or not generated Go binaries are stripped is determined by the build mode: `opt` strips them, `dbg` doesn't. There are cases in which we might want to avoid stripping binaries even when building them in `opt` mode - a notable example is to preserve the `.symtab` table, which [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) uses to perform a deeper analysis of whether vulnerable code is called by the binary.
Add an option to the plugin configuration, `strip_binaries`, that causes binaries to be stripped or not stripped regardless of the build mode. If a value is not set for `strip_binaries`, `go_binary` behaves as it does currently (i.e. stripping behaviour depends on the build mode).
=> Add `strip_binaries` configuration option

.plzconfig
This should fix a bug that is blocking the go-rules release workflow (see https://github.com/thought-machine/please/pull/3223).
=> Bump minimum Please version to v17.10.1

build_defs/cgo.build_defs
- we only need the mkdir command if we have a subdir
- was going to swap arguments to `find` since it moans sometimes but
- `go tool cgo` now supports `-trimpath` (it probably has for some time) so we can lose the find/xargs
=> Simplify cgo commands a little

plugins/BUILD
This fixes e2e test failures in environments where remote execution is enabled by default via a config file in `/etc/please/`.
=> Bump plugin-integration-testing plugin to v1.0.3

go.mod, go.sum
https://github.com/sourcegraph/scip-go uses plain golang tooling for indexing, which requires that all imported packages be included in the go.mod (even though under normal circumstances we rely on the packages in //third_party/go/BUILD)
=> Add some packages to go.mod so that the repository can be indexed with SCIP

.plzconfig, README.md, build_defs/go.build_defs
Go 1.20 made breaking changes to the way in which coverage is computed. This required the `coverageredesign` GOEXPERIMENT to be enabled when using go-rules with Go 1.20 onwards.
Go 1.19 has now been EOL for almost a year, and the `coveragedesign` GOEXPERIMENT will be removed from Go shortly, having been the default for around 18 months. Remove support for the pre-`coverageredesign` coverage method and the `coverageredesign` config field.
This increases the minimum Go version required by go-rules to 1.20.
=> Remove `coverageredesign` config field

tools/please_go/cover/cover.go, tools/please_go/install/toolchain/toolchain.go, tools/please_go/test/gotest.go, tools/please_go/test/write_test_main.go
They have changed how this works; presumably to facilitate the limitations of `linkname`. It does seem nicer.
I've run `cgo_test` in this repo & get a nonzero number of covered lines (the same as before) so it seems like it's still doing what it's supposed to.
=> Update coverage to support Go 1.23

build_defs/cgo.build_defs
This was missing from the CGO library, but is valid. The go_repo rules would generate cgo calls like this which came up for DataDog/zstd
=> Cgo asm srcs
